// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	scraper "github.com/tigorlazuardi/epub-scraper/scraper"
)

// Scraper is an autogenerated mock type for the Scraper type
type Scraper struct {
	mock.Mock
}

// Scrape provides a mock function with given fields: ctx, url
func (_m *Scraper) Scrape(ctx context.Context, url string) <-chan scraper.ScrapeData {
	ret := _m.Called(ctx, url)

	var r0 <-chan scraper.ScrapeData
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan scraper.ScrapeData); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan scraper.ScrapeData)
		}
	}

	return r0
}
