// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// Display is an autogenerated mock type for the Display type
type Display struct {
	mock.Mock
}

// Display provides a mock function with given fields:
func (_m *Display) Display() json.RawMessage {
	ret := _m.Called()

	var r0 json.RawMessage
	if rf, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	return r0
}
